[
  {
    "poster": {
      "poster_name": "Sergiy Isakov",
      "poster_handle": "seis"
    },
    "time_stamp": "2022-05-27 02:09:03",
    "text": "in my case I can’t even save it or deploy. Create settings api returns 404. Not sure if anyone here can help, seems like it’s a bug"
  },
  {
    "text": "Hello everyone\n\nCan you tell me why, when companies merge, the API can return information about a new object?\n\nAnd how can this be disabled?",
    "time_stamp": "2022-05-27 03:03:08"
  },
  {
    "poster": {
      "poster_name": "Muralidharan Arivagaran",
      "poster_handle": "muralidharan"
    },
    "time_stamp": "2022-05-27 03:25:32",
    "text": "Hi Folks!"
  },
  {
    "poster": {
      "poster_name": "Muralidharan Arivagaran",
      "poster_handle": "muralidharan"
    },
    "time_stamp": "2022-05-27 03:26:41",
    "text": "I am using get all deals api to retrieve all the deals. I am having a doubt that the deals are sorted based on which property created date or lastmodified date"
  },
  {
    "text": "Hello, @watchers\n\nI am facing an issue in CRM card creation, I created a card for the deal object on the test portal and everything worked perfectly fine there, we are creating a link through that card and displaying that generated link in the card only using the results array ( refer to this doc for more info: <https://developers.HubSpot.com/docs/api/crm/extensions/custom-cards>) but when I switched everything on the client's portal, the issue gets started, I am getting the card but when I am generating the link then the link is not displaying in the card but I can see everything working fine in the request body\n\nplease refer to the first screenshot, if the request URL is having everything that I want to show in the card then why the card is not displaying this thing\n\nand see second screenshot, this is how I need to show, also the thing is some time my code runs and shows the desired things but sometimes it doesn't work at all\n\n\nThanks in advance for your help, below is the code snippet\n\n$deal_id = ( !empty( $_GET['associatedObjectId'] ) ) ? $_GET['associatedObjectId'] : '';\n$userEmail = ( !empty( $_GET['userEmail'] ) ) ? $_GET['userEmail'] : '';\n\n$form_page_url = get_permalink( get_option( 'custom_link_form_page' ) );\n$custom_link_form_page_url = $form_page_url . '?deal_id=' . $deal_id .'&amp;userEmail'. $userEmail;\nglobal $wpdb;\n$sql_data = $wpdb-&gt;get_results( \"SELECT `id`, `product_array`, `created_date`, `modified_date`, `created_by`, `use`, `deal_id`, `checkout_link` FROM `wp_mwb_card_data` WHERE `random_string` = '\". $deal_id .\"' \" );\nforeach( $sql_data as $data ) {\n$checkout_link = $data-&gt;checkout_link;\n}\n\nif( ! empty( $checkout_link ) ) {\n$form_data = array(\n\"results\" =&gt; [\narray(\n\"objectId\" =&gt; $deal_id,\n\"title\" =&gt; $checkout_link,\n\"description\" =&gt; \"Created Link\",\n),\n],\n\"primaryAction\" =&gt; array(\n\"type\" =&gt; \"IFRAME\",\n\"width\" =&gt; 1100,\n\"height\" =&gt; 850,\n\"uri\" =&gt; $custom_link_form_page_url,\n\"label\" =&gt; \"Create Link\"\n),\n);\n} else {\n$form_data = array(\n\"results\" =&gt; [],\n\"primaryAction\" =&gt; array(\n\"type\" =&gt; \"IFRAME\",\n\"width\" =&gt; 1100,\n\"height\" =&gt; 850,\n\"uri\" =&gt; $custom_link_form_page_url,\n\"label\" =&gt; \"Create Link\"\n),\n);\n}\n$form_data_encoded = json_encode($form_data);\nprint_r($form_data_encoded);\n\n\nIn the above code, I am generating the link and saving it in the database then after checking the HubSpot's response and taking the deal id from there, processing that deal id further and checking in the database whether any link is generated for this deal or not in the past, if yes then just show the created link there, if no then show the crate link button again\n\nplease help me in this case",
    "time_stamp": "2022-05-27 07:01:15"
  },
  {
    "poster": {
      "poster_name": "Rajiv Subrahmanyam",
      "poster_handle": "rajiv"
    },
    "time_stamp": "2022-05-27 11:11:40",
    "text": "We started getting the following error on file upload via the API since this morning. It complains about the `access` field not being set, even though it is.\n```{\n    \"status\": \"error\",\n    \"message\": \"Invalid json {\\\"access\\\": \\\"PRIVATE\\\", \\\"overwrite\\\": true, \\\"duplicateValidationStrategy\\\": \\\"NONE\\\", \\\"duplicateValidationScope\\\": \\\"EXACT_FOLDER\\\"} for options string. Make sure required field \\\"access\\\" is set.\",\n    \"correlationId\": \"fd54c716-8ae7-4ffc-8467-89ff98d9cfa1\"\n}```\nDoes anyone else have this issue?",
    "reply_count": 3,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2022-05-27 14:56:31"
      },
      {
        "time_stamp": "2022-05-27 15:31:05"
      },
      {
        "time_stamp": "2022-05-27 15:50:24"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "ke",
      "poster_handle": "xj2610896"
    },
    "time_stamp": "2022-05-27 14:56:31",
    "text": "Yes we have some error on file upload. It complains about the `access`  invalid json"
  },
  {
    "poster": {
      "poster_name": "ke",
      "poster_handle": "xj2610896"
    },
    "time_stamp": "2022-05-27 15:31:05",
    "text": "I think is fix now"
  },
  {
    "poster": {
      "poster_name": "Rajiv Subrahmanyam",
      "poster_handle": "rajiv"
    },
    "time_stamp": "2022-05-27 15:50:24",
    "text": "FWIW, I was advised by HubSpot support to switch to using the /files endpoint (instead of /filemanager). <https://developers.HubSpot.com/docs/api/files/files>  . We did, and that worked for us. He also said that /filemanager may be deprecated."
  }
]