[
  {
    "poster": {
      "poster_name": "Andreas Meyer",
      "poster_handle": "a.meyer"
    },
    "time_stamp": "2020-12-07 01:37:03",
    "text": "Hi <@UFBNA9K9A>, thanks for making this clear. Then I missinterpreted the use of this property. I assume the order of the form fields in general can then only be achieved by the order, in which they are listed in the JSON file. Is that correct?\n\nThanks, Andi"
  },
  {
    "poster": {
      "poster_name": "Amy Parker",
      "poster_handle": "amyparker2401"
    },
    "time_stamp": "2020-12-07 04:00:16",
    "text": "Timestamp, Activity type, Local user, Remote user, Direction, Length",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-12-09 19:11:51"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Quentin Lamamy",
      "poster_handle": "quentin.lamamy"
    },
    "time_stamp": "2020-12-07 06:46:22",
    "text": "<@U01G17HBUP8> you should post what is exactly your need here : <https://community.HubSpot.com/t5/APIs-Integrations/bd-p/integrations>"
  },
  {
    "poster": {
      "poster_name": "Quentin Lamamy",
      "poster_handle": "quentin.lamamy"
    },
    "time_stamp": "2020-12-07 06:46:59",
    "text": "<@UBT0AHWLD> The HubSpot ui can’t be changed"
  },
  {
    "poster": {
      "poster_name": "Mo",
      "poster_handle": "geekyshood"
    },
    "time_stamp": "2020-12-07 10:05:04",
    "text": "Hello everyone, Please I am using the HubSpot ruby client, I authorized my client app using Oauth2, but upon making the request using the library i get this error: “The API key provided is invalid. View or manage your API key here: <https://app.HubSpot.com/l/api-key/>”"
  },
  {
    "poster": {
      "poster_name": "Mo",
      "poster_handle": "geekyshood"
    },
    "time_stamp": "2020-12-07 10:05:35",
    "text": "```@token = @HubSpot_tokens[\"access_token\"]\n                    config = ::HubSpot::Crm::Contacts::Configuration.new do |config|\n                        config.access_token = @token\n                    end\n                    \n                    api_client = ::HubSpot::Crm::Contacts::ApiClient.new(config)\n                    basic_api = ::HubSpot::Crm::Contacts::BasicApi.new(api_client)\n                    results = basic_api.get_by_id(contact_id: @id, auth_names: 'oauth2', limit: 10).to_hash```",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-12-09 19:13:42"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Mo",
      "poster_handle": "geekyshood"
    },
    "time_stamp": "2020-12-07 10:05:48",
    "text": "The above is a snippet of my code that returns that error."
  },
  {
    "text": "Hello, I created an app on a test account and I’m using the CRM cards feature. Our API returns an action to this card with this format:\n\n```{\n  \"type\": \"ACTION_HOOK\",\n  \"httpMethod\": \"POST\",\n  \"uri\": \"<https://example.com/action-hook>\",\n  \"label\": \"Example action\",\n  \"associatedObjectProperties\": [\n    \"some_crm_property\"\n  ]\n}```\nWhen I click on the action the response in the network tab is 401 for this URI:\n\n```<https://api.HubSpot.com/sales-objects/execution/v1/actions>```\nAny idea why this may be happening? Thanks!",
    "time_stamp": "2020-12-07 11:07:35",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-12-09 19:14:46"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Kathleen Emerson",
      "poster_handle": "kathleen"
    },
    "time_stamp": "2020-12-07 11:12:21",
    "text": "thank you for the reply! this seems like a good suggestion, thank you"
  },
  {
    "poster": {
      "poster_name": "Will Craig",
      "poster_handle": "will582"
    },
    "time_stamp": "2020-12-07 12:25:33",
    "text": "Hi all, apologize for pushing other individual's issues up on the channel - we are experiencing an issue with integrating a user on our platform (we use OAuth through HubSpot for login/signup).\n\nThe (free) user is not redirected back to our app but rather greeted with a message along the lines of \"User does not have permissions to authorize scopes\".\n\nWe've created test users in our own system, played around with permissions, and made other attempts to no avail. Has anyone ever fixed this issue? We only require the Contacts scope.",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-12-09 19:17:04"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Will Craig",
      "poster_handle": "will582"
    },
    "time_stamp": "2020-12-07 12:27:10",
    "edited": {
      "time_stamp": "2020-12-07 12:27:19"
    },
    "text": "As a follow-up, we saw this issue <https://community.HubSpot.com/t5/APIs-Integrations/403-user-does-not-have-permissions-to-authorize-scopes/td-p/231462|posted somewhere back in 2018> - wondering if there is an update",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-12-09 19:18:06"
      }
    ]
  }
]