[
  {
    "text": "While authenticating I'm getting this error even after updating the right redirect_url in the platform and code. Can anyone help me resolve this issue.",
    "time_stamp": "2024-06-03 10:48:43",
    "reply_count": 3,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-06-03 12:58:45"
      },
      {
        "time_stamp": "2024-06-03 22:16:18"
      },
      {
        "time_stamp": "2024-06-04 04:45:31"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Scott Marion",
      "poster_handle": "scott943"
    },
    "time_stamp": "2024-06-03 12:58:45",
    "text": "Did you update it in the app definition in your developer account in the app's Auth tab?  That is where it is looking for a match."
  },
  {
    "poster": {
      "poster_name": "Patrick Keo",
      "poster_handle": "patrick362"
    },
    "time_stamp": "2024-06-03 17:46:02",
    "text": "yeah there is a link rel=\"canonical\" that points to the homepage"
  },
  {
    "poster": {
      "poster_name": "Basavraj S Awatiger",
      "poster_handle": "basavraj.awatiger"
    },
    "time_stamp": "2024-06-03 22:16:18",
    "text": "yes, that is updated in app's auth tab and in code as well, but still getting the same error"
  }
]