[
  {
    "poster": {
      "poster_name": "Vamsi",
      "poster_handle": "vamsi"
    },
    "time_stamp": "2020-10-31 13:28:13",
    "text": "Hi Team, \n\nI’ve been trying to update Ecommbridge sync settings for our app since yesterday and nothing seems to work.\n\n \n\nI’m ending up with 500 Internal server error. I did try both the V1 and V2 endpoints according to their format suggestions.\n<https://api.hubapi.com/extensions/ecomm/v1/settings?appId=*****&amp;hapikey=*******>\n\n \n\n<https://api.hubapi.com/extensions/ecomm/v2/settings?appId=*****&amp;hapikey=*******>\n\n\nIt’s the same response for both the endpoints. Below are couple of error responses with correlation IDs.\n\n`{`\n    `\"status\": \"error\",`\n    `\"message\": \"com.HubSpot.apicaller.exceptions.ApiFailure: Api[name=integrations-sync, subPath=/settings/793] Had an unexpected error processing request.\",`\n    `\"correlationId\": \"07c7eb0b-4df0-4fd5-b181-d96b24d77e28\"`\n`}`\n`{`\n    `\"status\": \"error\",`\n    `\"message\": \"com.HubSpot.apicaller.exceptions.ApiFailure: Api[name=integrations-sync, subPath=/settings/793] Had an unexpected error processing request.\",`\n    `\"correlationId\": \"0689e247-f9d8-446b-9ebe-551e1cc22e0c\"`\n`}`\n`{`\n    `\"status\": \"error\",`\n    `\"message\": \"com.HubSpot.apicaller.exceptions.ApiFailure: Api[name=integrations-sync, subPath=/settings/793] Had an unexpected error processing request.\",`\n    `\"correlationId\": \"506f4585-4f15-4a12-ba10-8edb847446c1\"`\n`}`\n\n\nThis is important to us because we have new properties created and we need these mappings in order for the sync to work.\n\nPlease let me know if you need more information.\n---------------------------------\nOpened a ticked in the community too\n<https://community.HubSpot.com/t5/APIs-Integrations/Ecommbridge-Sync-Settings-not-getting-updated-500-Internal/m-p/383197#M37718>"
  }
]