[
  {
    "poster": {
      "poster_name": "Namratha Manjunath",
      "poster_handle": "nmanjunath"
    },
    "time_stamp": "2025-02-06 07:39:55",
    "text": "<@U0890C60VK6>: would you be interested in testing out the Sentry integration?\nCurrently, we're sending UIE log data to Sentry. You can set this up via Projects. We have just finished development and are looking for app partners to test it out. Yours might be a great use case. I'd love to talk more."
  },
  {
    "poster": {
      "poster_name": "Randy Segura",
      "poster_handle": "rsegura"
    },
    "time_stamp": "2025-02-06 11:00:48",
    "text": "Hey everyone,\n\nWe wanted to let you know about a visual regression with the `DescriptionList` component. Right now, it's always rendering in the \"column\" direction, even if you select \"row.\" Everything else with the component is still working as expected.\n\nWe’re aware of the issue and are actively working on a fix. Thanks for your patience, and we’ll keep you updated!",
    "reply_count": 7,
    "reply_users_count": 3,
    "replies": [
      {
        "time_stamp": "2025-02-07 05:35:36"
      },
      {
        "time_stamp": "2025-02-07 05:39:17"
      },
      {
        "time_stamp": "2025-02-07 05:42:10"
      },
      {
        "time_stamp": "2025-02-07 07:05:03"
      },
      {
        "time_stamp": "2025-02-07 07:05:38"
      },
      {
        "time_stamp": "2025-02-07 07:56:18"
      },
      {
        "time_stamp": "2025-02-09 21:22:54"
      }
    ]
  },
  {
    "text": "Hey everyone - I've picked up a project and taking over an existing UI Extension.  I've got everything setup but for some reason when running the extension locally, I am getting the following error.\n\n```[WARNING] 2025-02-07T05:28:41.407Z - App function \"getLineItems\" execution failed due to server internal error```\nThis is where I am see the issue...\n```      // Fetch line items using serverless function\n      const response = await runServerless({\n        name: \"getLineItems\",\n        parameters: { objectId: dealId },\n      });```\nI've checked and double checked graphQL query and this works on Postman and GraphiQL.\n\nThis should be the same code that is running in production which works - only when I run extension locally do I get the error.",
    "time_stamp": "2025-02-06 22:50:42",
    "reply_count": 4,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2025-02-07 03:46:17"
      },
      {
        "time_stamp": "2025-02-07 10:23:27"
      },
      {
        "time_stamp": "2025-02-07 10:28:05"
      },
      {
        "time_stamp": "2025-02-07 10:40:06"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Prakhar Agarwal",
      "poster_handle": "prakhar"
    },
    "time_stamp": "2025-02-07 00:13:27",
    "text": "Hey everyone, I am facing issue in fetching the data from my own backend setup using `HubSpot.fetch` method\n```const fetchWrapper = async &lt;T&gt;(\n  path: string,\n  options: {\n    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';\n    body?: {\n      [key: string | number]: unknown;\n    };\n  }\n) =&gt; {\n  const response = await HubSpot.fetch(`${BASE_URL}${path}`, {\n    ...options,\n    headers: {\n      Authorization: `Bearer ${AUTH_TOKEN}`,\n    },\n  });\n\n  if (!response.ok) {\n    throw new Error(`HTTP error! status: ${response.status}`);\n  }\n\n  return response.json() as Promise&lt;T&gt;;\n};```\nFor my `GET` request i am getting this error message in my backend\n`\"message\": \"Unexpected token '\\\"', \\\"\\\"\\\"\\\" is not valid JSON\",`\nIs there any parameter i am missing to add while fetching? This api works fine in postman and in my other applications. Please help me with a possible solution for this"
  }
]