[
  {
    "poster": {
      "poster_name": "Fabio Marchesi",
      "poster_handle": "fabio888"
    },
    "time_stamp": "2023-05-13 09:09:10",
    "text": "Hello. Looking support for *PATCH /cms/v3/blogs/posts/{objectId}*.\nI'm testing api call with python.\nI'm tryng to change internal name of a blog post but get this error message: *HTTP response body: {\"correlationId\":\"02563ab3-591d-4709-8b81-0266d5edda6f\",\"message\":\"internal error\",\"status\":\"error\"}*.\nThis is my code:\n`blog_post = BlogPost(id=\"68730591737\", name=\"My new internal name\")`\n`try:`\n    `api_response = client.cms.blogs.blog_posts.blog_post_api.update(object_id=\"objectId\", blog_post=blog_post)`\n    `pprint(api_response)`\n`except ApiException as e:`\n    `print(\"Exception when calling blog_posts_api-&gt;update: %s\\n\" % e)`\nI'm sure ID is correct.\nI'm sure I can talk to HS api becouse the blog post I'm trying to update has been cloned via python calling *POST /cms/v3/blogs/posts/clone*.\nI cannot understand what's wrong. Documentation (<https://developers.HubSpot.com/docs/api/cms/blog-post|link>) tells me that I have no need to specify all columns values (_All the column values need not be specified. Only the that need to be modified can be specified._).\nAnyone has an idea?\nTY"
  }
]